{% set name = "cuteFC" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cuteFC-{{ version }}.tar.gz
  sha256: c8cfc36d2b2195760d8feee2e3a8e79a885622c3e50f8ceb903d945d4e41e0ef

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - scipy
    - pysam
    - biopython
    - cigar
    - numpy
    - pyvcf3
    - scikit-learn

test:
  imports:
    - benchmarks
    - cuteFC
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tjiangHIT/cuteFC
  summary: Regenotyping structural variants through an accurate and efficient force-calling method
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Meltpinkg
